[project]
name = "federated-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fluke-fl>=0.7.9",
    "ipykernel>=7.1.0",
]
