data:
  client_split: 0.2
  dataset:
    name: mnist
    path: ./data
  distribution:
    name: dir
    beta: 0.02
  keep_test: true
  sampling_perc: 1.0
  server_split: 0.0
  server_test: true
  uniform_test: false
eval:
  eval_every: 1
  locals: false
  post_fit: true
  pre_fit: false
  server: true
  task: classification
exp:
  device: cpu
  seed: 42

logger:
  name: NewLog
  log_dir: (./logs)
  

protocol:
  eligible_perc: 0.2    # percentage of clients selected each round
  n_clients: 100
  n_rounds: 100
