hyperparameters:
  client:
    batch_size: 64
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1.0e-05
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    weighted: true
name: fluke.algorithms.fedavg.FedAVG
